<?xml version="1.0"?>
<package format="3">
  <name>ira_laser_tools</name>
  <version>0.1.0</version>
  <description>The ira_laser_tools package. These nodes are meant to provide some utils for lasers,
    like listen to different laser scan sources and merge them in a single scan or generate virtual
    laser scans from a pointcloud.</description>

  <url>http://www.ros.org/wiki/ira_laser_tools</url>
  <maintainer email="tomohiro.oku2023@gmail.com">Tomohiro Oku</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>generate_parameter_library</buildtool_depend>

  <depend>message_filters</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>